CREATE OR REPLACE TABLE `project_id.dataset.REORT_2` as 

SELECT *, 
       CASE WHEN PRICE BETWEEN 0 AND (AVG(PRICE) OVER (PARTITION BY POSTCODE,YEAR) - 1.5 * STDDEV(PRICE) OVER (PARTITION BY POSTCODE,YEAR)) THEN 1
            WHEN PRICE BETWEEN (AVG(PRICE) OVER (PARTITION BY POSTCODE,YEAR) - 1.5 * STDDEV(PRICE) OVER (PARTITION BY POSTCODE,YEAR)) AND AVG(PRICE) OVER (PARTITION BY POSTCODE,YEAR) THEN 2
            WHEN PRICE BETWEEN (AVG(PRICE) OVER (PARTITION BY POSTCODE,YEAR)) AND (AVG(PRICE) OVER (PARTITION BY POSTCODE,YEAR) + 1.5 * STDDEV(PRICE) OVER (PARTITION BY POSTCODE,YEAR))THEN 3
            ELSE 4
        END AS PRICE_BRACKET #CREATING PRICE BRACKETS BASE ON THE AVG OF PRICE AND STANDARD DEVIATION FOR POSTCODE AND YEAR
FROM (SELECT PRICE, 
             EXTRACT(YEAR FROM TRANSFER_DATE) AS YEAR,
             POSTCODE
      FROM`project_id.dataset.house_prices_CLEAN`)